---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart httpd
  service: name=httpd state=reloaded

- name: restart nginx
  service: name=nginx state=reloaded

- name: restart crontab
  service: name=cron state=reloaded
  
- name: restart sshd
  service: name=sshd state=restarted


- name: restart iptables
  service: name=iptables state=restarted
  
- name: restart crond
  service: name=crond state=restarted