- name: Copy backup selectel 
  copy: src=conf/backup/backup_selectel.sh dest=/srv/southbridge/bin/ owner=root group=root mode=0750
  tags: backup

- name: Copy backup selectel 
  copy: src=conf/backup/supload.sh dest=/srv/southbridge/bin/ owner=root group=root mode=0750
  tags: crond

- name: Copy backup selectel
  copy: src=conf/backup/backup-selectel.conf dest=/srv/southbridge/etc/ owner=root group=root mode=0600
  tags: crond


- name: Copy cron.d rules 
  copy: src=conf/backup/crond/ dest=/ owner=root group=root mode=0600
  notify:
  - restart crond
  tags: crond
